DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Models/ErrorViewModel.cs
using System;

namespace DotNetCoreMvc_AutoLotSite.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Controllers/HomeController.cs
using DotNetCoreMvc_AutoLotSite.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCoreMvc_AutoLotSite.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Controllers/InventoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using DotNetCore_AutoLotDAL.Models;
using DotNetCore_AutoLotDAL.Repos;

namespace DotNetCoreMvc_AutoLotSite.Controllers
{
    public class InventoryController : Controller
    {
        private readonly IInventoryRepo repo;

        public InventoryController(IInventoryRepo repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            return View("IndexWithViewComponent");
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var inventory = repo.GetOne(id);
            if(inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Make,Color,PetName")]Inventory inventory)
        {
            if (!ModelState.IsValid)
            {
                return View(inventory);
            }

            try
            {
                repo.Add(inventory);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to create the record: {ex.Message}");

                return View(inventory);
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var inventory = repo.GetOne(id);
            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, [Bind("Make,Color,PetName,Id,Timestamp")] Inventory inventory)
        {
            if(id == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View(inventory);
            }

            try
            {
                repo.Update(inventory);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to save the record. Another user has updated it. {ex.Message}");

                return View(inventory);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to save the record. {ex.Message}");
            }

            return RedirectToAction(nameof(Index));
        }

        public ActionResult Delete(int? id)
        {
            if(id == null)
            {
                return BadRequest();
            }

            var inventory = repo.GetOne(id);

            if (inventory == null)
            {
                return NotFound();
            }

            return View(inventory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete([Bind("Id,Timestamp")] Inventory inventory)
        {
            try
            {
                repo.Delete(inventory);
            }
            catch (DbUpdateConcurrencyException ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to delete the record. Another user has updated it. {ex.Message}");

                return View(inventory);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, $@"Unable to delete the record. {ex.Message}");
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/ViewComponents/InventoryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DotNetCore_AutoLotDAL.Repos;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace DotNetCoreMvc_AutoLotSite.ViewComponents
{
    public class InventoryViewComponent: ViewComponent
    {
        private readonly IInventoryRepo repo;

        public InventoryViewComponent(IInventoryRepo repo)
        {
            this.repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cars = repo.GetAll(x => x.Make, true);

            if(cars != null)
            {
                return View("InventoryPartialView", cars);
            }

            return new ContentViewComponentResult("Unable to lacate records");
        }
    }
}

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <email email-name="Support" email-domain="example.com"></email>
    <br />
    <email email-name="Marketing" email-domain="example.com"></email>
</address>

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Views/Inventory/Create.cshtml
@model DotNetCore_AutoLotDAL.Models.Inventory

@{
    var title = "Create";
    ViewData["Title"] = title;
}

<h2>@title</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            @Html.EditorForModel()
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Views/Inventory/Delete.cshtml
@model DotNetCore_AutoLotDAL.Models.Inventory

@{
    var title = "Delete";
    ViewData["Title"] = title;
}

<h2>@title</h2>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Make)</dt>
        <dd>@Html.DisplayFor(model => model.Make)</dd>

        <dt>@Html.DisplayNameFor(model => model.Color)</dt>
        <dd>@Html.DisplayFor(model => model.Color)</dd>

        <dt>@Html.DisplayNameFor(model => model.PetName)</dt>
        <dd>@Html.DisplayFor(model => model.PetName)</dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="Timestamp" />
        <input type="submit" value="Delete" class="btn btn-default" />
    </form>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Views/Inventory/Details.cshtml
@model DotNetCore_AutoLotDAL.Models.Inventory

@{
    var title = "Details";
    ViewData["Title"] = title;
}

<h2>@title</h2>
<div>
    <h4>Inventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Make)</dt>
        <dd>@Html.DisplayFor(model => model.Make)</dd>

        <dt>@Html.DisplayNameFor(model => model.Color)</dt>
        <dd>@Html.DisplayFor(model => model.Color)</dd>

        <dt>@Html.DisplayNameFor(model => model.PetName)</dt>
        <dd>@Html.DisplayFor(model => model.PetName)</dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Views/Inventory/DisplayTemplates/InventoryListItem.cshtml
@using DotNetCore_AutoLotDAL.Models
@model Inventory

<tr>
    <td>
        @Html.DisplayFor(model => model.Make)
    </td>
    <td>
        @Html.DisplayFor(model => model.Color)
    </td>
    <td>
        @Html.DisplayFor(model => model.PetName)
    </td>
    <td>
        <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-action="Details" asp-route-id="@Model.Id">Details</a> |
        <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
    </td>
</tr>

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Views/Inventory/Edit.cshtml
@model DotNetCore_AutoLotDAL.Models.Inventory

@{
    var title = "Edit";
    ViewData["Title"] = title;
}

<h2>@title</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Timestamp" />

            @Html.EditorForModel()

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{
    @{ 
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Views/Inventory/EditorTemplates/Inventory.cshtml
@using DotNetCore_AutoLotDAL.Models
@model Inventory

<h4>Inventory</h4>
<hr />
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
    <label asp-for="Make" class="control-label"></label>
    <input asp-for="Make" class="form-control" />
    <span asp-validation-for="Make" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Color" class="control-label"></label>
    <input asp-for="Color" class="form-control" />
    <span asp-validation-for="Color" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="PetName" class="control-label"></label>
    <input asp-for="PetName" class="form-control" />
    <span asp-validation-for="PetName" class="text-danger"></span>
</div>

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Views/Inventory/Index.cshtml
@using DotNetCore_AutoLotDAL.Models
@model IEnumerable<Inventory>

@functions
{
    public IList<Inventory> SortCars(IList<Inventory> cars)
    {
        var list = from s in cars orderby s.PetName select s;

        return list.ToList();
    }
}

@{ 
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Make)</th>
            <th>@Html.DisplayNameFor(model => model.Color)</th>
            <th>@Html.DisplayNameFor(model => model.PetName)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in SortCars(Model.ToList()))
        {
            @Html.DisplayFor(_ => item, "InventoryListItem")
        }
    </tbody>
</table>

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Views/Inventory/IndexWithViewComponent.cshtml
@using DotNetCore_AutoLotDAL.Models
@model IEnumerable<Inventory>

@functions
{
    public IList<Inventory> SortCars(IList<Inventory> cars)
    {
        var list = from s in cars orderby s.PetName select s;

        return list.ToList();
    }
}

@{ 
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
<p>
    <a asp-action="Create">Create New</a>
</p>
<vc:inventory></vc:inventory>

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Views/Shared/Components/Inventory/InventoryPartialView.cshtml
@using DotNetCore_AutoLotDAL.Models
@model IEnumerable<Inventory>

<table>
    <thead>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Make)
            </td>
            <td>
                @Html.DisplayNameFor(model => model.Color)
            </td>
            <td>
                @Html.DisplayNameFor(model => model.PetName)
            </td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ToList())
        {
        <tr>
            <td>
                @Html.DisplayFor(_ => item.Make)
            </td>
            <td>
                @Html.DisplayFor(_ => item.Color)
            </td>
            <td>
                @Html.DisplayFor(_ => item.PetName)
            </td>
            <td>
                <a asp-controller="Inventory" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-controller="Inventory" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-controller="Inventory" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

DotNetCoreMvc_AutoLot/DotNetCoreMvc_AutoLotSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotNetCoreMvc_AutoLotSite</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DotNetCoreMvc_AutoLotSite</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Inventory" asp-action="Index">Inventory</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - DotNetCoreMvc_AutoLotSite</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>